### ISSUE TITLE
Migrate alw integration artifact repositories to digiwf-core

### ISSUE THREAD

**Issue by lmoesle** [it-at-m/digiwf-alw-integration#11]
As a software developer I want to integrate the digiwf-alw-integration into the digiwf-core monorepository to simplify maintenance.

**Tasks**

* Add alw integration artifact to the `digiwf-integrations` package
* Configure `pom.xml`s to integrated the integration into the build mechanism
* `pom.xml` uses versions of shared packages from the parent (root pom in the digiwf-core)
* Migrate open issues from the repository to digiwf-core
* Archive old repository

**Criteria**

* Integration artifact is integrated into the digiwf-core monorepo
* Integration artifact is integrated into the build pipeline
* Issues are migrated to digiwf-core
* Old repository is archived
* Repository documentation is updated

**Comment by martind260** [comment]
done
